/***********************************************************************/
/*                                                                     */
/*  FILE        :intprg.c                                              */
/*  DATE        :Mon, May 10, 2010                                     */
/*  DESCRIPTION :Interrupt Program                                     */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.50).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

/*********************************************************************
*
* Device     : RX/RX600
*
* File Name  : intprg.c
*
* Abstract   : Interrupt Program.
*
* History    : 1.00  (2009-08-07)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright(c) 2009 Renesas Technology Corp.
*               And Renesas Solutions Corp.,All Rights Reserved. 
*
*********************************************************************/

#include "iodefine.h"
#include <machine.h>
#include "vect.h"

#pragma section IntPRG

// Exception(Supervisor Instruction)
//#pragma interrupt (Excep_SuperVisorInst)
void Excep_SuperVisorInst(void){/* brk(); */}

// Exception(Undefined Instruction)
//#pragma interrupt (Excep_UndefinedInst)
void Excep_UndefinedInst(void){/* brk(); */}

// Exception(Floating Point)
//#pragma interrupt (Excep_FloatingPoint)
void Excep_FloatingPoint(void){/* brk(); */}

// NMI
//#pragma interrupt (NonMaskableInterrupt)
void NonMaskableInterrupt(void){/* brk(); */}

// Dummy
//#pragma interrupt (Dummy)
void Dummy(void){/* brk(); */}

// BRK
//#pragma interrupt (Excep_BRK(vect=0))
void Excep_BRK(void){ wait(); }








